### ISSUE TITLE
iframe not ok on iOS with new version

### ISSUE THREAD

**Issue by problemadder** [TowelSniffer/Anki-Chess-2.0#40]
hi. thanks for the new version! I really appreciate it!
sadly there seems to be a problem on ios.

Screenshot from iOS on iPhone:
there is a "edge"/ too large frame on the down end. not on all cards but i cant recognize a pattern. seems to be random.
some cards are just fine. i tried to adjust css but had no luck (but no real clue what to do too :))
<img src="https://github.com/user-attachments/assets/dccd27ff-127f-4e4e-928a-2fd086ab2bcd" width="100" />

Screenshot from iOS on iPad:
![ipad](https://github.com/user-attachments/assets/b7a9b529-fdb0-4b3f-b4c5-4782a1e403c5)
the board is cut of in landscape "mode". was not the case with the previous Anki-chess-2.0 version.

bye

**Comment by TowelSniffer** [comment]
Yeah should be fixable. Got the day off so I will tinker with it after make a coffee

**Comment by TowelSniffer** [comment]
I think This should be solved. But with no IOS device I wont know unless someone else tests it as always. this way of handling the black/white border makes more sense anyway. managed to fix a display issue that was annoying me on Ankidroid while I was at it which is nice. Should work better for mobile devices in landscape mode. Let me know how it goes, I appreciate the help with testing for me.

**Comment by problemadder** [comment]
Hi,
Looks Perfect im iPhone now.
The issue on iPad is still the same but only in landscape mode.

**Comment by TowelSniffer** [comment]
good to know. are you able to tinker with these values for me and see if something works. try reducing 93vh in both instances. 

```
.mobile iframe {
  height: 93vh;
  width: min(93vh ,97vmin)
}

.mobile body {
  height: 93vh;
}
```

replacing this section entirely with the following should fix the overlap but

**Comment by problemadder** [comment]
"85" looks good on Mac, iPhone and iPad!

.mobile iframe {
  height: 85vh;
  width: min(85vh ,97vmin)
}

.mobile body {
  height: 85vh;
}


![Screenshot 2024-07-26 at 21 11 37](https://github.com/user-attachments/assets/58ddd41b-b61a-451e-a24e-153b7605bc76)

thanks for the help!

**Comment by TowelSniffer** [comment]
Thanks mate, I'm pretty sure anki supports iOS specific styling so I will include these values on next release

**Comment by TowelSniffer** [comment]
Styling has changed quite a bit recently, if someone can let me know their experiences on IOS i'd appreciate it

**Comment by hnvy** [comment]
Hello,

I'm happy to do testing on iPad iOS.

Currently, it looks like this:

![Image](https://github.com/user-attachments/assets/29423239-f409-49f1-824d-4814c460b9a5)

As seen, the pieces are not on the board.


Regards,

Harvey
